version: '3.8'

services:
  db:
    image: postgres:16
    container_name: conexblog-db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: conexblog
      POSTGRES_USER: postgres

volumes:
  postgres_data:
